version: "3.8"

services:
  elastiksearch:
    networks: home_server_internal_network

  logstash:
    networks: home_server_internal_network

  kibana:
    networks: home_server_internal_network

networks:
  home_server_internal_network:
    name: home_server_internal_network
    external: true
