version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=v88kJbWj79hqCLfooNEgbjATTfP
    ports:
      - 9200:9200
    networks:
      - home_server_internal_network

  fluentd:
    image: govtechsg/fluentd-elasticsearch
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - fluentd_data:/fluentd/log
    deploy:
      replicas: 2
    ports:
      - 24224:24224
      - 24224:24224/udp
    environment:
      - LOGSTASH_PREFIX=fluentd
      - ELASTIC_HOST=home_server_logging_stack_elasticsearch:9200
      - ELASTIC_PASSWORD=v88kJbWj79hqCLfooNEgbjATTfP
      - ELASTIC_USER=elastic
    networks:
      - home_server_internal_network

  kibana:
    image: kibana:8.11.1
    ports:
      - 5601:5601
    deploy:
      replicas: 2
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=v88kJbWj79hqCLfooNEgbjATTfP
    # secrets:
    #   - ELASTICSEARCH_PASSWORD
    networks:
      - home_server_internal_network

networks:
  home_server_internal_network:
    external: true

volumes:
  fluentd_data:
# secrets:
#   ELASTICSEARCH_PASSWORD:
#     external: true
