version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - home_server_internal_network

  fluentd:
    image: fluent/fluentd:latest
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - fluentd_data:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - home_server_internal_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - 5601:5601
    networks:
      - home_server_internal_network

networks:
  home_server_internal_network:
    external: true

volumes:
  fluentd_data:
