version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    networks:
      - home_server_internal_network
    ports:
      - 8096:8096
    volumes:
      - /home/sarthakjdev/servers/media-server/config:/config
      - /mnt/hdd0/media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=media.sarthakjdev.com

networks:
  home_server_internal_network:
    external: true
