version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    deploy:
      replicas: 2
    networks: home_server_internal_network

  grafana:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    deploy:
      replicas: 2
    networks: home_server_internal_network

volumes:
  prometheus-data:

networks:
  home_server_internal_network:
    - name: home_server_internal_network
    - external: true
