global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    bearer_token: "glc_eyJvIjoiOTU1OTEwIiwibiI6InN0YWNrLTc1MjcwMC1ncmFmYW5hLWFwaS10b2tlbi1pbnRlZ3JhdGlvbi1tZXRyaWNzcHVibGlzaGVyIiwiayI6ImRjbTJnYVEwNDQ5OU53NmExSzZuM2VRayIsIm0iOnsiciI6InByb2QtdXMtZWFzdC0wIn19"
