version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared
    secrets:
      - CF_TUNNEL_TOKEN
    command: tunnel --credentials-file /run/secrets/CF_TUNNEL_TOKEN run home-server-tunnel
    deploy:
      replicas: 2
    networks:
      - home_server_internal_network

secrets:
  CF_TUNNEL_TOKEN:
    external: true

networks:
  home_server_internal_network:
    external: true
