version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared
    secrets:
      - CF_TUNNEL_TOKEN
    command: tunnel --credentials-file /run/secrets/CF_TUNNEL_TOKEN run home-server-tunnel
    volumes:
      - /home/sarthakjdev/.cloudflared/cert.pem:/home/nonroot/.cloudflared/cert.pem:rw
      - ./config.yaml:/home/nonroot/.cloudflared/config.yaml:rw
      - /home/sarthakjdev/.cloudflared/home-server-tunnel.json:/home/nonroot/.cloudflared/home-server-tunnel.json:rw
    deploy:
      replicas: 2
    networks:
      - home_server_internal_network
    environment:
      - TUNNEL_ORIGIN_CERT=~/.cloudflared/cert.pem

secrets:
  CF_TUNNEL_TOKEN:
    external: true

networks:
  home_server_internal_network:
    external: true
