version: "3.8"

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - home_server_internal_network

volumes:
  nextcloud_data:
    external: true

networks:
  home_server_internal_network:
    external: true
