version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - ./nginx/conf.d:/etc/nginx/conf.d
    #   - ./ssl:/etc/nginx/ssl:ro
    #   - ./.htpsswd:/etc/nginx/.htpsswd
    networks:
      - home_server_internal_network

networks:
  home_server_internal_network:
    external: true
