version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html:z
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - home_server_internal_network

networks:
  home_server_internal_network:
    external: true
