version: "3.8"

services:
  nextcloud_postgress_db:
    image: postgres
    volumes:
      - nextcloud_postgress_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/NEXTCLOUD_PG_DB
      - POSTGRES_USER_FILE=/run/secrets/NEXTCLOUD_PG_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/NEXTCLOUD_PG_PASSWORD
    secrets:
      - NEXTCLOUD_PG_DB
      - NEXTCLOUD_PG_PASSWORD
      - NEXTCLOUD_PG_USER
    networks:
      - home_server_internal_network

  nextcloud:
    image: nextcloud:fpm
    ports:
      - 9000:9000
    volumes:
      - nextcloud:/var/www/html
    deploy:
      replicas: 2
    environment:
      - POSTGRES_HOST=home_file_server_stack_nextcloud_postgress_db
      - POSTGRES_DB_FILE=/run/secrets/NEXTCLOUD_PG_DB
      - POSTGRES_USER_FILE=/run/secrets/NEXTCLOUD_PG_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/NEXTCLOUD_PG_PASSWORD
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/NEXTCLOUD_ADMIN_USER
    secrets:
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_PG_DB
      - NEXTCLOUD_PG_PASSWORD
      - NEXTCLOUD_PG_USER
    networks:
      - home_server_internal_network

volumes:
  nextcloud_postgress_db_volume:
  nextcloud:

networks:
  home_server_internal_network:
    external: true

secrets:
  NEXTCLOUD_ADMIN_PASSWORD:
    external: true
  NEXTCLOUD_ADMIN_USER:
    external: true
  NEXTCLOUD_PG_DB:
    external: true
  NEXTCLOUD_PG_PASSWORD:
    external: true
  NEXTCLOUD_PG_USER:
    external: true
