version: "3.8"

services:
  dns:
    image: andyshinn/dnsmasq:2.83
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 53:53
    networks:
      - home_server_internal_network
    deploy:
      replicas: 2

networks:
  home_server_internal_network:
    external: true
