version: "3.8"

services:
  dns:
    image: andyshinn/dnsmasq:2.83
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - home_server_internal_network
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

networks:
  home_server_internal_network:
    external: true
